name: sca_ui
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  stacked:
  http:
  line_icons: ^0.2.0
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.3
  fluttertoast: ^7.1.5
  get_it: ^5.0.3
  flutter_email_sender: ^4.0.0
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: opensans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Italic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Light.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-LightItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBoldItalic.ttf
    - family: worksans
      fonts:
        - asset: assets/fonts/worksans/WorkSans-Black.ttf
        - asset: assets/fonts/worksans/WorkSans-BlackItalic.ttf
        - asset: assets/fonts/worksans/WorkSans-Bold.ttf
        - asset: assets/fonts/worksans/WorkSans-BoldItalic.ttf
        - asset: assets/fonts/worksans/WorkSans-ExtraBold.ttf
        - asset: assets/fonts/worksans/WorkSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/worksans/WorkSans-ExtraLight.ttf
        - asset: assets/fonts/worksans/WorkSans-ExtraLightItalic.ttf
        - asset: assets/fonts/worksans/WorkSans-Italic.ttf
        - asset: assets/fonts/worksans/WorkSans-Light.ttf
        - asset: assets/fonts/worksans/WorkSans-LightItalic.ttf
        - asset: assets/fonts/worksans/WorkSans-Medium.ttf
        - asset: assets/fonts/worksans/WorkSans-MediumItalic.ttf
        - asset: assets/fonts/worksans/WorkSans-Regular.ttf
        - asset: assets/fonts/worksans/WorkSans-SemiBold.ttf
        - asset: assets/fonts/worksans/WorkSans-SemiBoldItalic.ttf
        - asset: assets/fonts/worksans/WorkSans-Thin.ttf
        - asset: assets/fonts/worksans/WorkSans-ThinItalic.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
